# Site settings
author: Rachel Taylor
title: The Journey
header-img: img/home-bg.png
email: rachmaybe@gmail.com
copyright_name: Rachel Taylor
description: > # this means to ignore newlines until "baseurl:"
  Buckle up, it's a wild ride!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rachel-taylor

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
